### PR TITLE
Properly ignore days in progress stats

### PR DESCRIPTION
**Pull request by rathrio**
Addresses #9.

Changes:

- Empty days with comments are no longer removed when punch reformats the month, e.g. when using `punch -f` or after using `punch --remove ...`.
- The progress stats now disregards hours in ignored days. Note that the normal total output, e.g. the output of `punch` still shows the actual total.
- Improved workdays stat:
  - Old: "Workdays left:  2"
  - New: "Workdays left: 2/16"
- Minor doc updates
- Rubocop config fix

### CODE REVIEW

**Comment by rathrio** [comment]
@GodlikeSpam0r would you mind reviewing these changes? Do the stats look as intended on this branch with your files?

**Comment by sam-e-ch** [comment]
Code looks nice and ignored days really aren't used for the stats.

However, I noticed another bug (or feature?) in the stats:
Work on weekends is not counted.

Am I not allowed to work on weekends? :smile:

**Comment by rathrio** [comment]
@GodlikeSpam0r good catch! I broke it in this PR by only summing up the workday totals 🙈 (which are by default mon-fri)

Fix incoming.

**Comment by sam-e-ch** [comment]
LGTM now

**Pull request merged**
